apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZbWwwWjI5eVltOTJjMnQ1T21kb2NGOUpkRVZPUzJsYWVEVndlVTlOUzFSdWVEUkdhelJ3YW0xaFRrWlpaVUkwVm5SaFlqTT0ifX19Cg==
type: kubernetes.io/dockerconfigjson
